services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - ./backend/.env
    network_mode: host

  frontend:
    build:
      context: ./frontend/apps/web
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - backend
    env_file:
      - ./frontend/apps/web/.env
